---
# This will search and add 'SSLHostConfig' TLSv1.2+ to server.conf file to remediate TLS vulnerability
- name: TLS Tomcat Remediation
  hosts: VSPM_TLS

  tasks:
    - name: Replacing SSLProtocol line in server.xml file
      ansible.builtin.lineinfile:
        path: '/opt/tomcat9/conf/server.xml'
        regexp: '^.*<SSLHostConfig>*$'
        line: '        <SSLHostConfig protocol="TLSv1.2+TLSv1.3">'
        backup: true
        backrefs: true

    - name: restart tomcat service
      ansible.builtin.service:
       name: tomcat.service
       state: restarted