---
# This will return a 404 Forbidden message when trying OPTIONS or TRACE.
- name: TLS Remediation
  hosts: VSPM_TLS

  tasks:
    - name: "Adding TLS conditions"
      ansible.builtin.blockinfile:
        path: '/etc/nginx/nginx.conf'
        block: | 
          #        ssl_protocols TLSv1.2 TLSv1.3;
          #        ssl_prefer_server_ciphers on;
        insertafter: '^#        ssl_ciphers PROFILE*\{$'
        backup: true
  
    - name: restart nginx service
      ansible.builtin.service:
        name: nginx
        state: restarted