# This will search for any backups Ansible created durring remediation and implement it
- name: TLS Tomcat Backout
  hosts: VSPM_TLS

  vars:
    server_file: '/opt/tomcat9/conf/server.xml'

  tasks:
    - name: "Find all backups for {{ server_file }}"
      ansible.builtin.find:
        recurse: no
        path:
          - "{{ server_file | dirname }}"
        patterns:
          - '{{ server_file | basename }}\..*~'
        use_regex: true
      register: find_backup

    - name: Select the latest backup
      ansible.builtin.set_fact:
        latest_backup: "{{ (find_backup.files | sort(attribute='mtime') | last).path }}"

    - name: Show the latest backup
      ansible.builtin.debug:
        var: latest_backup

    - name: "Restore latest backup of {{ server_file }}"
      ansible.builtin.copy:
        src: "{{ latest_backup }}"
        remote_src: true
        dest: "{{ server_file }}"

    - name: restart tomcat service
      ansible.builtin.service:
        name: httpd
        state: restarted