---
# This will search and replace 'SSLProtocl' line in http.conf file to remediate TLS vulnerability
- name: TLS Remediation
  hosts: TLS_hosts

  tasks:
    - name: stop http service
      ansible.builtin.service:
       name: httpd
       state: stopped

    - name: Replacing SSLProtocol line in http.conf file
      ansible.builtin.lineinfile:
        path: '/etc/httpd/conf.d/https.conf'
        regexp: '^.*SSLProtocol.*$'
        line: '    SSLProtocol -ALL +TLSv1.2'
        backup: true
        backrefs: true

    - name: start http service
      ansible.builtin.service:
       name: httpd
       state: started
