---
# This will search for any backups Ansible created durring remediation and implement it
- name: TLS Backout
  hosts: VSPM_TLS_Backout

  vars:
    http_file: '/etc/httpd/conf.d/https.conf'

  tasks:
    - name: "Find all backups for {{ http_file }}"
      ansible.builtin.find:
        recurse: no
        path:
          - "{{ http_file | dirname }}"
        patterns:
          - '{{ http_file | basename }}\..*~'
        use_regex: true
      register: find_backup

    - name: Select the latest backup
      ansible.builtin.set_fact:
        latest_backup: "{{ (find_backup.files | sort(attribute='mtime') | last).path }}"

    - name: Show the latest backup
      ansible.builtin.debug:
        var: latest_backup

    - name: stop http service
      ansible.builtin.service:
       name: httpd
       state: stopped

    - name: "Restore latest backup of {{ http_file }}"
      ansible.builtin.copy:
        src: "{{ latest_backup }}"
        remote_src: true
        dest: "{{ http_file }}"

    - name: start http service
      ansible.builtin.service:
       name: httpd
       state: started